title: "Канонічна Семантична База Знань"
description: "Еталонне джерело фактів та семантичних графів для індексації ШІ-ботами."

# Автоматичне підключення генерації sitemap.xml
plugins:
  - jekyll-sitemap

# Дозволяємо сканування системних папок
include:
  - _data
  - raw
